"""Tests for SING-BOX JSON config builder."""

import json

from app.issuance.singbox_config import (
    _parse_vless_link,
    _vless_link_to_outbound,
    build_singbox_config,
)
from app.issuance.vless_provider import VlessServerConfig


# Realistic VLESS links matching the formats generated by _build_vless_link
_TCP_REALITY_LINK = (
    "vless://test-uuid@1.2.3.4:443"
    "?type=tcp&security=reality"
    "&pbk=test-pbk&fp=chrome&sni=www.google.com"
    "&sid=test-sid&spx=%2F&flow=xtls-rprx-vision"
    "#🇫🇮 Helsinki"
)

_WS_TLS_LINK = (
    "vless://test-uuid@ws.example.com:443"
    "?type=ws&security=tls&path=%2Fws-path"
    "&host=ws.example.com&fp=chrome&sni=ws.example.com"
    "#🇩🇪 Frankfurt"
)

_XHTTP_REALITY_LINK = (
    "vless://test-uuid@5.6.7.8:443"
    "?type=xhttp&security=reality&path=%2Fxhttp-path"
    "&pbk=xhttp-pbk&fp=chrome&sni=www.microsoft.com"
    "&sid=xhttp-sid&spx=%2F"
    "#🇺🇸 Los Angeles"
)


def _make_servers(*links: str) -> tuple[VlessServerConfig, ...]:
    return tuple(
        VlessServerConfig(
            server_label=f"Server-{i}",
            country_code="XX",
            country_flag="🏁",
            vless_link=link,
        )
        for i, link in enumerate(links)
    )


class TestParseVlessLink:
    def test_tcp_reality(self):
        p = _parse_vless_link(_TCP_REALITY_LINK)
        assert p["uuid"] == "test-uuid"
        assert p["host"] == "1.2.3.4"
        assert p["port"] == 443
        assert p["type"] == "tcp"
        assert p["security"] == "reality"
        assert p["pbk"] == "test-pbk"
        assert p["sid"] == "test-sid"
        assert p["sni"] == "www.google.com"
        assert p["flow"] == "xtls-rprx-vision"
        assert p["label"] == "\U0001f1eb\U0001f1ee Helsinki"

    def test_ws_tls(self):
        p = _parse_vless_link(_WS_TLS_LINK)
        assert p["type"] == "ws"
        assert p["security"] == "tls"
        assert p["path"] == "/ws-path"
        assert p["host_header"] == "ws.example.com"

    def test_xhttp_reality(self):
        p = _parse_vless_link(_XHTTP_REALITY_LINK)
        assert p["type"] == "xhttp"
        assert p["security"] == "reality"
        assert p["path"] == "/xhttp-path"
        assert p["flow"] == ""


class TestVlessLinkToOutbound:
    def test_tcp_reality_outbound(self):
        ob = _vless_link_to_outbound(_TCP_REALITY_LINK)
        assert ob["type"] == "vless"
        assert ob["server"] == "1.2.3.4"
        assert ob["server_port"] == 443
        assert ob["uuid"] == "test-uuid"
        assert ob["flow"] == "xtls-rprx-vision"
        assert ob["tls"]["enabled"] is True
        assert ob["tls"]["reality"]["enabled"] is True
        assert ob["tls"]["reality"]["public_key"] == "test-pbk"
        assert ob["tls"]["reality"]["short_id"] == "test-sid"
        assert "transport" not in ob

    def test_ws_tls_outbound(self):
        ob = _vless_link_to_outbound(_WS_TLS_LINK)
        assert ob["type"] == "vless"
        assert ob["server"] == "ws.example.com"
        assert ob["tls"]["enabled"] is True
        assert ob["tls"]["server_name"] == "ws.example.com"
        assert ob["transport"]["type"] == "ws"
        assert ob["transport"]["path"] == "/ws-path"
        assert ob["transport"]["headers"]["Host"] == "ws.example.com"
        assert "flow" not in ob

    def test_xhttp_reality_outbound(self):
        ob = _vless_link_to_outbound(_XHTTP_REALITY_LINK)
        assert ob["type"] == "vless"
        assert ob["server"] == "5.6.7.8"
        assert ob["transport"]["type"] == "splithttp"
        assert ob["transport"]["path"] == "/xhttp-path"
        assert ob["tls"]["reality"]["enabled"] is True
        assert ob["tls"]["reality"]["public_key"] == "xhttp-pbk"


class TestBuildSingboxConfig:
    def test_empty_servers(self):
        result = build_singbox_config(tuple())
        parsed = json.loads(result)
        assert parsed["outbounds"] == []

    def test_single_server(self):
        servers = _make_servers(_TCP_REALITY_LINK)
        result = build_singbox_config(servers)
        parsed = json.loads(result)

        # Check outbounds structure
        tags = [ob["tag"] for ob in parsed["outbounds"]]
        assert "proxy" in tags
        assert "direct" in tags
        assert "block" in tags
        assert "dns-out" in tags

        # Selector should list the server tag
        selector = next(ob for ob in parsed["outbounds"] if ob["type"] == "selector")
        assert selector["default"] == selector["outbounds"][0]

    def test_multiple_servers(self):
        servers = _make_servers(_TCP_REALITY_LINK, _WS_TLS_LINK, _XHTTP_REALITY_LINK)
        result = build_singbox_config(servers)
        parsed = json.loads(result)

        vless_outbounds = [ob for ob in parsed["outbounds"] if ob["type"] == "vless"]
        assert len(vless_outbounds) == 3

        selector = next(ob for ob in parsed["outbounds"] if ob["type"] == "selector")
        assert len(selector["outbounds"]) == 3

    def test_xhttp_uses_splithttp_transport(self):
        servers = _make_servers(_XHTTP_REALITY_LINK)
        result = build_singbox_config(servers)
        parsed = json.loads(result)
        vless_outbounds = [ob for ob in parsed["outbounds"] if ob["type"] == "vless"]
        assert len(vless_outbounds) == 1
        assert vless_outbounds[0]["transport"]["type"] == "splithttp"

    def test_russian_domain_bypass_rules(self):
        servers = _make_servers(_TCP_REALITY_LINK)
        result = build_singbox_config(servers)
        parsed = json.loads(result)

        rules = parsed["route"]["rules"]
        domain_rule = next(
            (r for r in rules if "domain_suffix" in r),
            None,
        )
        assert domain_rule is not None
        assert ".ru" in domain_rule["domain_suffix"]
        assert ".su" in domain_rule["domain_suffix"]
        assert ".рф" in domain_rule["domain_suffix"]
        assert domain_rule["outbound"] == "direct"

    def test_dns_rule(self):
        servers = _make_servers(_TCP_REALITY_LINK)
        result = build_singbox_config(servers)
        parsed = json.loads(result)

        rules = parsed["route"]["rules"]
        dns_rule = next(
            (r for r in rules if r.get("protocol") == "dns"),
            None,
        )
        assert dns_rule is not None
        assert dns_rule["outbound"] == "dns-out"

    def test_default_route_is_proxy(self):
        servers = _make_servers(_TCP_REALITY_LINK)
        result = build_singbox_config(servers)
        parsed = json.loads(result)

        assert parsed["route"]["final"] == "proxy"
        assert parsed["route"]["auto_detect_interface"] is True

    def test_valid_json(self):
        servers = _make_servers(_TCP_REALITY_LINK, _WS_TLS_LINK)
        result = build_singbox_config(servers)
        parsed = json.loads(result)
        assert isinstance(parsed, dict)
        assert "outbounds" in parsed
        assert "route" in parsed
