"""Чистые помощники транспортной границы (slice 1): нормализация и маппинг представления."""

from __future__ import annotations

from app.bot_transport.dispatcher import Slice1Dispatcher, dispatch_slice1_transport
from app.bot_transport.message_catalog import (
    RenderedMessagePackage,
    render_telegram_outbound_plan,
)
from app.bot_transport.normalized import (
    NormalizationRejectReason,
    NormalizedSlice1Bootstrap,
    NormalizedSlice1Buy,
    NormalizedSlice1Help,
    NormalizedSlice1Menu,
    NormalizedSlice1Plans,
    NormalizedSlice1Rejected,
    NormalizedSlice1Renew,
    NormalizedSlice1ResendAccess,
    NormalizedSlice1Result,
    NormalizedSlice1Status,
    NormalizedSlice1Success,
    NormalizedSlice1SupportContact,
    NormalizedSlice1SupportMenu,
    TransportIncomingEnvelope,
    normalize_command_token,
    parse_slice1_transport,
)
from app.bot_transport.outbound import (
    OutboundKeyboardMarker,
    OutboundMessageKey,
    OutboundNextActionKey,
    OutboundPlanCategory,
    TelegramOutboundPlan,
    map_transport_safe_to_outbound_plan,
)
from app.bot_transport.presentation import (
    TransportAccessResendCode,
    TransportHelpCode,
    TransportNextActionHint,
    TransportResponseCategory,
    TransportSafeResponse,
    TransportStatusCode,
    TransportStorefrontCode,
    TransportSupportCode,
    map_bootstrap_identity_to_transport,
    map_get_subscription_status_to_transport,
    map_slice1_help_to_transport,
    map_slice1_support_to_transport,
)
from app.bot_transport.runtime_facade import (
    Slice1TelegramRuntimeFacade,
    handle_slice1_telegram_update_to_rendered_message,
)
from app.bot_transport.runtime_wrapper import (
    Slice1TelegramRuntimeWrapper,
    TelegramRuntimeAction,
    TelegramRuntimeActionKind,
    extract_eligible_private_chat_id_from_telegram_like_update,
    handle_slice1_telegram_update_to_runtime_action,
)
from app.bot_transport.service import Slice1TelegramService, handle_slice1_telegram_update
from app.bot_transport.telegram_adapter import (
    TelegramAdapterRejected,
    TelegramAdapterRejectReason,
    extract_slice1_envelope_from_telegram_update,
)

__all__ = [
    "NormalizationRejectReason",
    "NormalizedSlice1Bootstrap",
    "NormalizedSlice1Buy",
    "NormalizedSlice1Help",
    "NormalizedSlice1Menu",
    "NormalizedSlice1Plans",
    "NormalizedSlice1Rejected",
    "NormalizedSlice1Renew",
    "NormalizedSlice1ResendAccess",
    "NormalizedSlice1Result",
    "NormalizedSlice1Status",
    "NormalizedSlice1Success",
    "NormalizedSlice1SupportContact",
    "NormalizedSlice1SupportMenu",
    "OutboundKeyboardMarker",
    "OutboundMessageKey",
    "OutboundNextActionKey",
    "OutboundPlanCategory",
    "RenderedMessagePackage",
    "Slice1Dispatcher",
    "Slice1TelegramRuntimeFacade",
    "Slice1TelegramRuntimeWrapper",
    "Slice1TelegramService",
    "TelegramAdapterRejectReason",
    "TelegramAdapterRejected",
    "TelegramOutboundPlan",
    "TelegramRuntimeAction",
    "TelegramRuntimeActionKind",
    "TransportAccessResendCode",
    "TransportHelpCode",
    "TransportIncomingEnvelope",
    "TransportNextActionHint",
    "TransportResponseCategory",
    "TransportSafeResponse",
    "TransportStatusCode",
    "TransportStorefrontCode",
    "TransportSupportCode",
    "dispatch_slice1_transport",
    "extract_eligible_private_chat_id_from_telegram_like_update",
    "extract_slice1_envelope_from_telegram_update",
    "handle_slice1_telegram_update",
    "handle_slice1_telegram_update_to_rendered_message",
    "handle_slice1_telegram_update_to_runtime_action",
    "map_bootstrap_identity_to_transport",
    "map_get_subscription_status_to_transport",
    "map_slice1_help_to_transport",
    "map_slice1_support_to_transport",
    "map_transport_safe_to_outbound_plan",
    "normalize_command_token",
    "parse_slice1_transport",
    "render_telegram_outbound_plan",
]
