"""Admin support boundary (ADM-01 and related); contracts + orchestration slice."""

from app.admin_support.adm01_endpoint import (
    Adm01EndpointResponse,
    Adm01InboundRequest,
    Adm01OutboundSummary,
    execute_adm01_endpoint,
)
from app.admin_support.adm01_identity_resolve_adapter import Adm01IdentityResolveAdapter
from app.admin_support.adm01_lookup import Adm01LookupHandler
from app.admin_support.adm01_postgres_issuance_read_adapter import Adm01PostgresIssuanceReadAdapter
from app.admin_support.adm01_subscription_policy_read_adapter import (
    Adm01SubscriptionPolicyReadAdapter,
)
from app.admin_support.adm01_wiring import (
    build_adm01_entitlement_read_from_postgres_snapshots,
    build_adm01_internal_lookup_http_app,
    build_adm01_issuance_read_from_postgres_issuance_state,
    build_adm01_lookup_handler,
    build_adm01_policy_read_from_postgres_snapshots,
)
from app.admin_support.adm02_billing_facts_ledger_adapter import (
    Adm02BillingFactsLedgerReadAdapter,
)
from app.admin_support.adm02_diagnostics import ADM02_CAPABILITY_CLASS, Adm02DiagnosticsHandler
from app.admin_support.adm02_endpoint import (
    Adm02DiagnosticsHandlerLike,
    Adm02EndpointResponse,
    Adm02InboundRequest,
    Adm02OutboundSummary,
    execute_adm02_endpoint,
)
from app.admin_support.adm02_ensure_access import (
    Adm02EnsureAccessHandler,
    NoopAdm02EnsureAccessAuditSink,
)
from app.admin_support.adm02_ensure_access_audit_logging import (
    FanoutAdm02EnsureAccessAuditSink,
    StructuredLoggingAdm02EnsureAccessAuditSink,
)
from app.admin_support.adm02_ensure_access_audit_postgres import (
    PostgresAdm02EnsureAccessAuditSink,
)
from app.admin_support.adm02_ensure_access_audit_read import (
    Adm02EnsureAccessAuditLookupHandler,
)
from app.admin_support.adm02_ensure_access_audit_read_endpoint import (
    Adm02EnsureAccessAuditLookupEndpointResponse,
    Adm02EnsureAccessAuditLookupEvidenceItem,
    Adm02EnsureAccessAuditLookupHandlerLike,
    Adm02EnsureAccessAuditLookupInboundRequest,
    execute_adm02_ensure_access_audit_lookup_endpoint,
)
from app.admin_support.adm02_ensure_access_endpoint import (
    Adm02EnsureAccessEndpointResponse,
    Adm02EnsureAccessHandlerLike,
    Adm02EnsureAccessInboundRequest,
    Adm02EnsureAccessOutboundSummary,
    execute_adm02_ensure_access_endpoint,
)
from app.admin_support.adm02_ensure_access_mutation import (
    Adm02EnsureAccessIssuanceMutationAdapter,
    FixedAdm02MutationOptIn,
)
from app.admin_support.adm02_fact_of_access_audit_adapter import (
    Adm02FactOfAccessPersistenceAuditAdapter,
)
from app.admin_support.adm02_identity_resolve_adapter import Adm02IdentityResolveAdapter
from app.admin_support.adm02_postgres_ensure_access_audit_read_adapter import (
    Adm02PostgresEnsureAccessAuditReadAdapter,
)
from app.admin_support.adm02_quarantine_mismatch_adapter import Adm02QuarantineMismatchReadAdapter
from app.admin_support.adm02_reconciliation_runs_adapter import Adm02ReconciliationRunsReadAdapter
from app.admin_support.adm02_wiring import (
    build_adm02_ensure_access_audit_lookup_handler,
    build_adm02_ensure_access_handler,
    build_adm02_internal_diagnostics_http_app,
    build_adm02_internal_support_http_app,
)
from app.admin_support.authorization import AllowlistAdm01Authorization, AllowlistAdm02Authorization
from app.admin_support.contracts import (
    Adm01AuthorizationPort,
    Adm01EntitlementReadPort,
    Adm01IdentityResolvePort,
    Adm01IssuanceReadPort,
    Adm01LookupInput,
    Adm01LookupOutcome,
    Adm01LookupResult,
    Adm01LookupSummary,
    Adm01PolicyReadPort,
    Adm01RedactionPort,
    Adm01SubscriptionReadPort,
    Adm01SubscriptionStatusSummary,
    Adm01SupportAccessReadinessBucket,
    Adm01SupportNextAction,
    Adm01SupportReadinessSummary,
    Adm01SupportSubscriptionBucket,
    Adm02AuthorizationPort,
    Adm02BillingFactsCategory,
    Adm02BillingFactsDiagnostics,
    Adm02BillingFactsReadPort,
    Adm02DiagnosticsInput,
    Adm02DiagnosticsOutcome,
    Adm02DiagnosticsResult,
    Adm02DiagnosticsSummary,
    Adm02EnsureAccessAuditEvent,
    Adm02EnsureAccessAuditEventType,
    Adm02EnsureAccessAuditEvidenceItem,
    Adm02EnsureAccessAuditLookupInput,
    Adm02EnsureAccessAuditLookupOutcome,
    Adm02EnsureAccessAuditLookupResponse,
    Adm02EnsureAccessAuditOutcomeBucket,
    Adm02EnsureAccessAuditPort,
    Adm02EnsureAccessAuditPrincipalMarker,
    Adm02EnsureAccessAuditReadPort,
    Adm02EnsureAccessAuditReadQuery,
    Adm02EnsureAccessAuditReadResult,
    Adm02EnsureAccessAuthorizationPort,
    Adm02EnsureAccessInput,
    Adm02EnsureAccessMutationPort,
    Adm02EnsureAccessOutcome,
    Adm02EnsureAccessRemediationResult,
    Adm02EnsureAccessResult,
    Adm02EnsureAccessSummary,
    Adm02FactOfAccessAuditPort,
    Adm02FactOfAccessAuditRecord,
    Adm02FactOfAccessDisclosureCategory,
    Adm02MutationOptInPort,
    Adm02QuarantineDiagnostics,
    Adm02QuarantineMarker,
    Adm02QuarantineReadPort,
    Adm02QuarantineReasonCode,
    Adm02ReconciliationDiagnostics,
    Adm02ReconciliationReadPort,
    Adm02ReconciliationRunMarker,
    Adm02RedactionPort,
    AdminActorRef,
    AdminPolicyFlag,
    AdminTargetLookup,
    EntitlementSummary,
    EntitlementSummaryCategory,
    InternalAdminPrincipalExtractionInput,
    InternalAdminPrincipalExtractionOutcome,
    InternalAdminPrincipalExtractionResult,
    InternalAdminPrincipalExtractor,
    InternalUserTarget,
    IssuanceOperationalState,
    IssuanceOperationalSummary,
    RedactionMarker,
    TelegramUserTarget,
)

__all__ = [
    "ADM02_CAPABILITY_CLASS",
    "Adm01AuthorizationPort",
    "Adm01EndpointResponse",
    "Adm01EntitlementReadPort",
    "Adm01IdentityResolveAdapter",
    "Adm01IdentityResolvePort",
    "Adm01InboundRequest",
    "Adm01IssuanceReadPort",
    "Adm01LookupHandler",
    "Adm01LookupInput",
    "Adm01LookupOutcome",
    "Adm01LookupResult",
    "Adm01LookupSummary",
    "Adm01OutboundSummary",
    "Adm01PolicyReadPort",
    "Adm01PostgresIssuanceReadAdapter",
    "Adm01RedactionPort",
    "Adm01SubscriptionPolicyReadAdapter",
    "Adm01SubscriptionReadPort",
    "Adm01SubscriptionStatusSummary",
    "Adm01SupportAccessReadinessBucket",
    "Adm01SupportNextAction",
    "Adm01SupportReadinessSummary",
    "Adm01SupportSubscriptionBucket",
    "Adm02AuthorizationPort",
    "Adm02BillingFactsCategory",
    "Adm02BillingFactsDiagnostics",
    "Adm02BillingFactsLedgerReadAdapter",
    "Adm02BillingFactsReadPort",
    "Adm02DiagnosticsHandler",
    "Adm02DiagnosticsHandlerLike",
    "Adm02DiagnosticsInput",
    "Adm02DiagnosticsOutcome",
    "Adm02DiagnosticsResult",
    "Adm02DiagnosticsSummary",
    "Adm02EndpointResponse",
    "Adm02EnsureAccessAuditEvent",
    "Adm02EnsureAccessAuditEventType",
    "Adm02EnsureAccessAuditEvidenceItem",
    "Adm02EnsureAccessAuditLookupEndpointResponse",
    "Adm02EnsureAccessAuditLookupEvidenceItem",
    "Adm02EnsureAccessAuditLookupHandler",
    "Adm02EnsureAccessAuditLookupHandlerLike",
    "Adm02EnsureAccessAuditLookupInboundRequest",
    "Adm02EnsureAccessAuditLookupInput",
    "Adm02EnsureAccessAuditLookupOutcome",
    "Adm02EnsureAccessAuditLookupResponse",
    "Adm02EnsureAccessAuditOutcomeBucket",
    "Adm02EnsureAccessAuditPort",
    "Adm02EnsureAccessAuditPrincipalMarker",
    "Adm02EnsureAccessAuditReadPort",
    "Adm02EnsureAccessAuditReadQuery",
    "Adm02EnsureAccessAuditReadResult",
    "Adm02EnsureAccessAuthorizationPort",
    "Adm02EnsureAccessEndpointResponse",
    "Adm02EnsureAccessHandler",
    "Adm02EnsureAccessHandlerLike",
    "Adm02EnsureAccessInboundRequest",
    "Adm02EnsureAccessInput",
    "Adm02EnsureAccessIssuanceMutationAdapter",
    "Adm02EnsureAccessMutationPort",
    "Adm02EnsureAccessOutboundSummary",
    "Adm02EnsureAccessOutcome",
    "Adm02EnsureAccessRemediationResult",
    "Adm02EnsureAccessResult",
    "Adm02EnsureAccessSummary",
    "Adm02FactOfAccessAuditPort",
    "Adm02FactOfAccessAuditRecord",
    "Adm02FactOfAccessDisclosureCategory",
    "Adm02FactOfAccessPersistenceAuditAdapter",
    "Adm02IdentityResolveAdapter",
    "Adm02InboundRequest",
    "Adm02MutationOptInPort",
    "Adm02OutboundSummary",
    "Adm02PostgresEnsureAccessAuditReadAdapter",
    "Adm02QuarantineDiagnostics",
    "Adm02QuarantineMarker",
    "Adm02QuarantineMismatchReadAdapter",
    "Adm02QuarantineReadPort",
    "Adm02QuarantineReasonCode",
    "Adm02ReconciliationDiagnostics",
    "Adm02ReconciliationReadPort",
    "Adm02ReconciliationRunMarker",
    "Adm02ReconciliationRunsReadAdapter",
    "Adm02RedactionPort",
    "AdminActorRef",
    "AdminPolicyFlag",
    "AdminTargetLookup",
    "AllowlistAdm01Authorization",
    "AllowlistAdm02Authorization",
    "EntitlementSummary",
    "EntitlementSummaryCategory",
    "FanoutAdm02EnsureAccessAuditSink",
    "FixedAdm02MutationOptIn",
    "InternalAdminPrincipalExtractionInput",
    "InternalAdminPrincipalExtractionOutcome",
    "InternalAdminPrincipalExtractionResult",
    "InternalAdminPrincipalExtractor",
    "InternalUserTarget",
    "IssuanceOperationalState",
    "IssuanceOperationalSummary",
    "NoopAdm02EnsureAccessAuditSink",
    "PostgresAdm02EnsureAccessAuditSink",
    "RedactionMarker",
    "StructuredLoggingAdm02EnsureAccessAuditSink",
    "TelegramUserTarget",
    "build_adm01_entitlement_read_from_postgres_snapshots",
    "build_adm01_internal_lookup_http_app",
    "build_adm01_issuance_read_from_postgres_issuance_state",
    "build_adm01_lookup_handler",
    "build_adm01_policy_read_from_postgres_snapshots",
    "build_adm02_ensure_access_audit_lookup_handler",
    "build_adm02_ensure_access_handler",
    "build_adm02_internal_diagnostics_http_app",
    "build_adm02_internal_support_http_app",
    "execute_adm01_endpoint",
    "execute_adm02_endpoint",
    "execute_adm02_ensure_access_audit_lookup_endpoint",
    "execute_adm02_ensure_access_endpoint",
]
